// repo actions
export const GET_REPOS_REQUEST = "GET_REPOS_RESUQEST";
export const GET_REPOS_REQUEST_SUCCESS = "GET_REPOS_REQUEST_SUCCESS";
export const GET_REPOS_REQUEST_FAILED = "GET_REPOS_REQUEST_FAILED";

// user actions
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_REQUEST_SUCCESS = "GET_USERS_REQUEST_SUCCESS";
export const GET_USERS_REQUEST_FAILED = "GET_USERS_REQUEST_FAILED";

// bookmark-actions
