// repo actions
export const GET_REPOS_REQUEST = "GET_REPOS_RESUQEST";
export const GET_REPOS_REQUEST_SUCCESS = "GET_REPOS_REQUEST_SUCCESS";
export const GET_REPOS_REQUEST_FAILED = "GET_REPOS_REQUEST_FAILED";
export const GET_REPO_CONTENT_REQUEST = "GET_REPO_CONTENT_REQUEST";
export const GET_REPO_CONTENT_REQUEST_SUCCESS =
  "GET_REPO_CONTENT_REQUEST_SUCCESS";
export const GET_REPO_CONTENT_REQUEST_FAILED =
  "GET_REPO_CONTENT_REQUEST_FAILED";
export const GET_REPO_REQUEST = "GET_REPO_REQUEST";
export const GET_REPO_REQUEST_SUCCESS = "GET_REPO_REQUEST_SUCCESS";
export const GET_REPO_REQUEST_FAILED = "GET_REPO_REQUEST_FAILED";
export const GET_PULL_COUNT_REQUEST = "GET_PULL_COUNT_REQUEST";
export const GET_PULL_COUNT_REQUEST_SUCCESS = "GET_PULL_COUNT_REQUEST_SUCCESS";
export const GET_PULL_COUNT_REQUEST_FAILED = "GET_PULL_COUNT_REQUEST_FAILED";
export const GET_BRANCH_COUNT_REQUEST = "GET_BRANCH_COUNT_REQUEST";
export const GET_BRANCH_COUNT_REQUEST_SUCCESS =
  "GET_BRANCH_COUNT_REQUEST_SUCCESS";
export const GET_BRANCH_COUNT_REQUEST_FAILED =
  "GET_BRANCH_COUNT_REQUEST_FAILED";

// user actions
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_REQUEST_SUCCESS = "GET_USERS_REQUEST_SUCCESS";
export const GET_USERS_REQUEST_FAILED = "GET_USERS_REQUEST_FAILED";

// bookmark-actions
